AccumulatedAnnualDemand:
    indices: [REGION,COMMODITY,YEAR]
    type: param
    dtype: float
    default: 0
AnnualEmissionLimit:
    indices: [REGION,EMISSION,YEAR]
    type: param
    dtype: float
    default: 999999
InputToNewCapacityRatio:
    indices: [REGION,TECHNOLOGY,COMMODITY,YEAR]
    type: param
    dtype: float
    default: 0
InputToNewCapacity:
    indices: [REGION,TECHNOLOGY,COMMODITY,YEAR]
    type: result
    dtype: float
    default: 0
UDCMultiplierTotalCapacity:
    indices: [REGION,TECHNOLOGY,UDC,YEAR]
    type: param
    dtype: float
    default: 0
UDCMultiplierNewCapacity:
    indices: [REGION,TECHNOLOGY,UDC,YEAR]
    type: param
    dtype: float
    default: 0
UDCMultiplierActivity:
    indices: [REGION,TECHNOLOGY,UDC,YEAR]
    type: param
    dtype: float
    default: 0
UDCConstant:
    indices: [REGION,UDC,YEAR]
    type: param
    dtype: float
    default: 0
UDCTag:
    indices: [REGION,UDC]
    type: param
    dtype: int
    default: -1
InputToTotalCapacityRatio: 
    indices: [REGION,TECHNOLOGY,COMMODITY,YEAR]
    type: param
    dtype: float
    default: 0
InputToTotalCapacity: 
    indices: [REGION,TECHNOLOGY,COMMODITY,YEAR]
    type: result
    dtype: float
    default: 0
TechnologyActivityByModeLowerLimit:
    short_name: TechActivityByModeLowerLimit
    indices: [REGION,TECHNOLOGY,MODE_OF_OPERATION,YEAR]
    type: param
    dtype: float
    default: 0
TechnologyActivityByModeUpperLimit:
    short_name: TechActivityByModeUpperLimit
    indices: [REGION,TECHNOLOGY,MODE_OF_OPERATION,YEAR]
    type: param
    dtype: float
    default: 0
TechnologyActivityDecreaseByModeLimit:
    short_name: TechActivityDecreaseByModeLimit
    indices: [REGION,TECHNOLOGY,MODE_OF_OPERATION,YEAR]
    type: param
    dtype: float
    default: 0
TechnologyActivityIncreaseByModeLimit:
    short_name: TechActivityIncreaseByModeLimit
    indices: [REGION,TECHNOLOGY,MODE_OF_OPERATION,YEAR]
    type: param
    dtype: float
    default: 0                        
AvailabilityFactor:
    indices: [REGION,TECHNOLOGY,YEAR]
    type: param
    dtype: float
    default: 1
CapacityFactor:
    indices: [REGION,TECHNOLOGY,TIMESLICE,YEAR]
    type: param
    dtype: float
    default: 1
CapacityOfOneTechnologyUnit:
    indices: [REGION,TECHNOLOGY,YEAR]
    type: param
    dtype: float
    default: 0
CapacityToActivityUnit:
    indices: [REGION,TECHNOLOGY]
    type: param
    dtype: float
    default: 1
CapitalCost:
    indices: [REGION,TECHNOLOGY,YEAR]
    type: param
    dtype: float
    default: 0
CapitalCostStorage:
    indices: [REGION,STORAGE,YEAR]
    type: param
    dtype: float
    default: 0
ResidualStorageCapacity:
    indices: [REGION,STORAGE,YEAR]
    type: param
    dtype: float
    default: 0
MinStorageCharge:
    indices: [REGION,STORAGE,YEAR]
    type: param
    dtype: float
    default: 0
TechnologyToStorage:
    indices: [REGION, TECHNOLOGY, STORAGE, MODE_OF_OPERATION]
    type: param
    dtype: int
    default: 0
StorageLevelStart:
    indices: [REGION, STORAGE]
    type: param
    dtype: float
    default: 1
TechnologyFromStorage:
    indices: [REGION, TECHNOLOGY, STORAGE, MODE_OF_OPERATION]
    type: param
    dtype: int
    default: 0
UDC:
    dtype: str
    type: set   
DiscountRate:
    indices: [REGION]
    type: param
    dtype: float
    default: 0.05
DiscountRateIdv:
    indices: [REGION,TECHNOLOGY]
    type: param
    dtype: float
    default: 0.05
EMISSION:
    dtype: str
    type: set
EmissionActivityRatio:
    indices: [REGION,TECHNOLOGY,EMISSION,MODE_OF_OPERATION,YEAR]
    type: param
    dtype: float
    default: 0
EmissionsPenalty:
    indices: [REGION,EMISSION,YEAR]
    type: param
    dtype: float
    default: 0
FixedCost:
    indices: [REGION,TECHNOLOGY,YEAR]
    type: param
    dtype: float
    default: 0
COMMODITY:
    dtype: str
    type: set
InputActivityRatio:
    indices: [REGION,TECHNOLOGY,COMMODITY,MODE_OF_OPERATION,YEAR]
    type: param
    dtype: float
    default: 0
SEASON:
    dtype: int
    type: set
MODE_OF_OPERATION:
    dtype: int
    type: set
ModelPeriodEmissionLimit:
    indices: [REGION,EMISSION]
    type: param
    dtype: float
    default: 999999
EmissionToActivityChangeRatio:
    indices: [REGION,TECHNOLOGY,EMISSION,MODE_OF_OPERATION,YEAR]
    type: param
    dtype: float
    default: 0                              
OperationalLife:
    indices: [REGION,TECHNOLOGY]
    type: param
    dtype: float
    default: 1
OperationalLifeStorage:
    indices: [REGION,STORAGE]
    type: param
    dtype: float
    default: 0
OutputActivityRatio:
    indices: [REGION,TECHNOLOGY,COMMODITY,MODE_OF_OPERATION,YEAR]
    type: param
    dtype: float
    default: 0
REGION:
    dtype: str
    type: set
ResidualCapacity:
    indices: [REGION,TECHNOLOGY,YEAR]
    type: param
    dtype: float
    default: 0
SpecifiedAnnualDemand:
    indices: [REGION,COMMODITY,YEAR]
    type: param
    dtype: float
    default: 0
SpecifiedDemandProfile:
    indices: [REGION,COMMODITY,TIMESLICE,YEAR]
    type: param
    dtype: float
    default: 0
STORAGE:
    dtype: str
    type: set
DAYTYPE:
    dtype: int
    type: set
DAILYTIMEBRACKET:
    dtype: int
    type: set
STORAGEINTRADAY:
    dtype: int
    type: set
STORAGEINTRAYEAR:
    dtype: int
    type: set
TECHNOLOGY:
    dtype: str
    type: set
TIMESLICE:
    dtype: str
    type: set
TotalAnnualMaxCapacity:
    indices: [REGION,TECHNOLOGY,YEAR]
    type: param
    dtype: float
    default: 999999
TotalAnnualMaxCapacityInvestment:
    short_name: TotalAnnualMaxCapacityInvestmen
    indices: [REGION,TECHNOLOGY,YEAR]
    type: param
    dtype: float
    default: 999999
TotalAnnualMinCapacity:
    indices: [REGION,TECHNOLOGY,YEAR]
    type: param
    dtype: float
    default: 0
TotalAnnualMinCapacityInvestment:
    short_name: TotalAnnualMinCapacityInvestmen
    indices: [REGION,TECHNOLOGY,YEAR]
    type: param
    dtype: float
    default: 0
TotalTechnologyAnnualActivityLowerLimit:
    short_name: TotalTechnologyAnnualActivityLo
    indices: [REGION,TECHNOLOGY,YEAR]
    type: param
    dtype: float
    default: 0
TotalTechnologyAnnualActivityUpperLimit:
    short_name: TotalTechnologyAnnualActivityUp
    indices: [REGION,TECHNOLOGY,YEAR]
    type: param
    dtype: float
    default: 999999
TotalTechnologyModelPeriodActivityLowerLimit:
    short_name: TotalTechnologyModelPeriodActLo
    indices: [REGION,TECHNOLOGY]
    type: param
    dtype: float
    default: 0
TotalTechnologyModelPeriodActivityUpperLimit:
    short_name: TotalTechnologyModelPeriodActUp
    indices: [REGION,TECHNOLOGY]
    type: param
    dtype: float
    default: 999999
TradeRoute:
    indices: [REGION,COMMODITY,YEAR]
    type: param
    dtype: float
    default: 0
VariableCost:
    indices: [REGION,TECHNOLOGY,MODE_OF_OPERATION,YEAR]
    type: param
    dtype: float
    default: 0
YEAR:
    dtype: int
    type: set
YearSplit:
    indices: [TIMESLICE,YEAR]
    type: param
    dtype: float
    default: 0
AnnualEmissions:
    indices: [REGION,EMISSION,YEAR]
    type: result
    dtype: float
    default: 0
AccumulatedNewCapacity:
    indices: [REGION, TECHNOLOGY, YEAR]
    type: result
    dtype: float
    default: 0
AnnualFixedOperatingCost:
    indices: [REGION, TECHNOLOGY, YEAR]
    type: result
    dtype: float
    default: 0
AnnualTechnologyEmission:
    indices: [REGION, TECHNOLOGY, EMISSION, YEAR]
    type: result
    dtype: float
    default: 0
AnnualizedInvestmentCost:
    indices: [REGION, TECHNOLOGY, YEAR]
    type: result
    dtype: float
    default: 0
AnnualTechnologyEmissionByMode:
    indices: [REGION, TECHNOLOGY, EMISSION, MODE_OF_OPERATION, YEAR]
    type: result
    dtype: float
    default: 0
AnnualVariableOperatingCost:
    indices: [REGION, TECHNOLOGY, YEAR]
    type: result
    dtype: float
    default: 0
CapitalInvestment:
    indices: [REGION, TECHNOLOGY, YEAR]
    type: result
    dtype: float
    default: 0
Demand:
    indices: [REGION, TIMESLICE, COMMODITY, YEAR]
    type: result
    dtype: float
    default: 0
DiscountedSalvageValue:
    indices: [REGION, TECHNOLOGY, YEAR]
    type: result
    dtype: float
    default: 0
DiscountedTechnologyEmissionsPenalty:
    short_name: DiscountedTechEmissionsPenalty
    indices: [REGION, TECHNOLOGY, YEAR]
    type: result
    dtype: float
    default: 0
TechnologyEmissionsPenalty:
    short_name: TechEmissionsPenalty
    indices: [REGION, TECHNOLOGY, YEAR]
    type: result
    dtype: float
    default: 0
NewCapacity:
    indices: [REGION, TECHNOLOGY, YEAR]
    type: result
    dtype: float
    default: 0
NumberOfNewTechnologyUnits:
    indices: [REGION, TECHNOLOGY, YEAR]
    type: result
    dtype: float
    default: 0
ProductionByTechnology:
    indices: [REGION, TIMESLICE, TECHNOLOGY, COMMODITY, YEAR]
    type: result
    dtype: float
    default: 0
ProductionByTechnologyAnnual:
    indices: [REGION, TECHNOLOGY, COMMODITY, YEAR]
    type: result
    dtype: float
    default: 0
RateOfActivity:
    indices: [REGION, TIMESLICE, TECHNOLOGY, MODE_OF_OPERATION, YEAR]
    type: result
    dtype: float
    default: 0
RateOfProductionByTechnology:
    indices: [REGION, TIMESLICE, TECHNOLOGY, COMMODITY, YEAR]
    type: result
    dtype: float
    default: 0
RateOfProductionByTechnologyByMode:
    short_name: RateOfProductionByTechByMode
    indices: [REGION, TIMESLICE, TECHNOLOGY, MODE_OF_OPERATION, COMMODITY, YEAR]
    type: result
    dtype: float
    default: 0
RateOfUseByTechnology:
    indices: [REGION, TIMESLICE, TECHNOLOGY, COMMODITY, YEAR]
    type: result
    dtype: float
    default: 0
RateOfUseByTechnologyByMode:
    indices: [REGION, TIMESLICE, TECHNOLOGY, MODE_OF_OPERATION, COMMODITY, YEAR]
    type: result
    dtype: float
    default: 0
SalvageValue:
    indices: [REGION, TECHNOLOGY, YEAR]
    type: result
    dtype: float
    default: 0
SalvageValueStorage:
    indices: [REGION, STORAGE, YEAR]
    type: result
    dtype: float
    default: 0
TotalAnnualTechnologyActivityByMode:
    short_name: TotalAnnualTechActivityByMode
    indices: [REGION, TECHNOLOGY, MODE_OF_OPERATION, YEAR]
    type: result
    dtype: float
    default: 0
TotalCapacityAnnual:
    indices: [REGION, TECHNOLOGY, YEAR]
    type: result
    dtype: float
    default: 0
TotalDiscountedCost:
    indices: [REGION,YEAR]
    type: result
    dtype: float
    default: 0
TotalTechnologyAnnualActivity:
    indices: [REGION, TECHNOLOGY, YEAR]
    type: result
    dtype: float
    default: 0
TotalTechnologyModelPeriodActivity:
    short_name: TotalTechModelPeriodActivity
    indices: [REGION, TECHNOLOGY]
    type: result
    dtype: float
    default: 0
Trade:
    indices: [REGION, REGION, TIMESLICE, COMMODITY, YEAR]
    type: result
    dtype: float
    default: 0
UseByTechnology:
    indices: [REGION, TIMESLICE, TECHNOLOGY, COMMODITY, YEAR]
    type: result
    dtype: float
    default: 0
UseByTechnologyAnnual:
    indices: [REGION, TECHNOLOGY, COMMODITY, YEAR]
    type: result
    dtype: float
    default: 0
Conversionls:
    indices: [TIMESLICE, SEASON]
    type: param
    dtype: int
    default: 1
Conversionld:
    indices: [TIMESLICE, DAYTYPE]
    type: param
    dtype: int
    default: 1
Conversionlh:
    indices: [TIMESLICE, DAILYTIMEBRACKET]
    type: param
    dtype: int
    default: 1
DaysInDayType:
    indices: [SEASON, DAYTYPE, YEAR]
    type: param
    dtype: int
    default: 1
DaySplit:
    indices: [DAILYTIMEBRACKET, YEAR]
    type: param
    dtype: int
    default: 1